/* Main.ino file generated by New Project wizard
 *
 * Created:   Sun May 30 2021
 * Processor: Arduino Nano
 * Compiler:  Arduino AVR (Proteus)
 */

// Peripheral Configuration Code (do not edit)
//---CONFIG_BEGIN---
#pragma GCC push_options
#pragma GCC optimize ("Os")

#include <core.h> // Required by cpu
#include <cpu.h>

#pragma GCC pop_options

// Peripheral Constructors
CPU &cpu = Cpu;

void peripheral_setup () {
}

void peripheral_loop() {
}
//---CONFIG_END---

void setup () {
peripheral_setup();
// TODO: put your setup code here, to run once:
}=